#!/bin/sh
#
# Copyright (C) 2011-2012 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/uboot-envtools.sh
. /lib/functions.sh

block_dev_path() {
	local dev_path

	case "$1" in
	/dev/mmcblk*)
		dev_path="$1"
		;;
	PARTLABEL=* | PARTUUID=*)
		dev_path=$(blkid -t "$1" -o device)
		[ -z "${dev_path}" -o $? -ne 0 ] && return 1
		;;
	*)
		return 1;
		;;
	esac

	echo "${dev_path}"
	return 0
}

board=$(board_name)

case "$board" in
cmcc,rax3000m-emmc* | mediatek,*-emmc-rfb | mediatek,*-emmc-re-cp-*)
	env_dev=$(cat /sys/module/boot_param/parameters/env_part 2>/dev/null)
	[ -n "$env_dev" ] && env_dev=$(block_dev_path "${env_dev}")
	[ -z "$env_dev" ] && env_dev=$(block_dev_path "PARTLABEL=u-boot-env")
	[ -n "$env_dev" ] && \
		ubootenv_add_uci_config "$env_dev" "0" "0x80000"
	;;
*360,t7* |\
livinet,zr-3020*)
	ubootenv_add_uci_config "/dev/mtd2" "0x0" "0x20000" "0x20000" "1"
	;;
h3c,nx30pro |\
*clt,r30b1* |\
cmcc,rax3000m)
	ubootenv_add_uci_config "/dev/mtd2" "0x0" "0x80000" "0x20000" "4"
	;;
*imou,lc-hx3001*)
	ubootenv_add_uci_config "/dev/mtd2" "0x0" "0x80000" "0x80000" "1"
	;;
xiaomi,mi-router-wr30u* |\
xiaomi,redmi-router-ax6000*)
	ubootenv_add_uci_config "/dev/mtd2" "0x0" "0x10000" "0x20000" "1"
	;;
*konka,komi-a31*)
	ubootenv_add_uci_config "/dev/mtd2" "0x0" "0x20000" "0x80000" "1"
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
