#!/bin/sh

dev=br-lan

stop_qos() {
	tc qdisc del dev $dev root 2>/dev/null
	tc qdisc del dev $dev ingress 2>/dev/null
	tc qdisc del dev ${dev}-ifb root 2>/dev/null
	ip link del dev ${dev}-ifb 2>/dev/null
}

start_qos() {
	local dl=$1
	local up=$2
	
	tc qdisc add dev $dev root handle 1: htb
	tc class add dev $dev parent 1: classid 1:1 htb rate ${dl}mbit
	
	ip link add dev ${dev}-ifb name ${dev}-ifb type ifb
	ip link set dev ${dev}-ifb up
	
	tc qdisc add dev ${dev}-ifb root handle 1: htb
	tc class add dev ${dev}-ifb parent 1: classid 1:1 htb rate ${up}mbit
	
	tc qdisc add dev $dev ingress
	tc filter add dev $dev parent ffff: protocol ip u32 match u32 0 0 flowid 1:1 action mirred egress redirect dev ${dev}-ifb
}

case "$1" in
	"stop")
		stop_qos
		iptables -t mangle -D FORWARD  -j eqos
		echo 0 > /sys/kernel/debug/hnat/qos_toggle
		sed -i '/\/etc\/init.d\/eqos start/d' /etc/firewall.user
		iptables -t mangle -D FORWARD -i br-lan -j DSCP --set-dscp 0
		iptables -t mangle -D FORWARD -o br-lan -j DSCP --set-dscp 0
		ip6tables -t mangle -D FORWARD -i br-lan -j DSCP --set-dscp 0
		ip6tables -t mangle -D FORWARD -o br-lan -j DSCP --set-dscp 0
		echo "10 0" > /sys/kernel/debug/hnat/hnat_setting
		for i in $(seq 0 7); do
		echo 0 0 0 0 0 0 0 > $hqos_path/qdma_txq$i
		done
		for i in $(seq 8 15); do
		echo 1 0 0 0 0 0 0 > $hqos_path/qdma_txq$i
		done	
	;;
	"start")
		stop_qos
		ip6tables -t mangle -D FORWARD -i br-lan -j DSCP --set-dscp 0
		ip6tables -t mangle -D FORWARD -o br-lan -j DSCP --set-dscp 0
		ip6tables -t mangle -A FORWARD -i br-lan -j DSCP --set-dscp 0
		ip6tables -t mangle -A FORWARD -o br-lan -j DSCP --set-dscp 0
		iptables -t mangle -D FORWARD -i br-lan -j DSCP --set-dscp 0
		iptables -t mangle -D FORWARD -o br-lan -j DSCP --set-dscp 0
		iptables -t mangle -A FORWARD -i br-lan -j DSCP --set-dscp 0
		iptables -t mangle -A FORWARD -o br-lan -j DSCP --set-dscp 0
		start_qos $2 $3
		iptables -t mangle -N eqos
		iptables -t mangle -F eqos
		iptables -t mangle -D FORWARD  -j eqos
		iptables -t mangle -A FORWARD  -j eqos
		echo 1 > /sys/kernel/debug/hnat/qos_toggle
		echo 0 wrr 10000000 > /sys/kernel/debug/hnat/qdma_sch0
		echo 0 wrr 10000000 > /sys/kernel/debug/hnat/qdma_sch1
		echo 0 wrr 10000000 > /sys/kernel/debug/hnat/qdma_sch2
		echo 0 wrr 10000000 > /sys/kernel/debug/hnat/qdma_sch3
		echo 0 0 0 0 0 4 4 > /sys/kernel/debug/hnat/qdma_txq0
		echo 1 0 0 0 0 4 4 > /sys/kernel/debug/hnat/qdma_txq8
		sed -i '/\/etc\/init.d\/eqos start/d' /etc/firewall.user
		echo "/etc/init.d/eqos start" >> /etc/firewall.user
		echo "10 1" > /sys/kernel/debug/hnat/hnat_setting
	;;
	"add")
		ip="$2"
		dl="$3"
		up="$4"
		id="$5" idpair=$((id+32))
		cnt=$(tc class show dev $dev | wc -l)
		if [ $id -lt 32 ]; then
		
		iptables -t mangle -D eqos -s $ip -j DSCP --set-dscp ${id}
		iptables -t mangle -D eqos -d $ip -j DSCP --set-dscp ${idpair}
		if [ $up -ne 0 ]; then
		echo 2 0 0 1 ${up} 4 4 > /sys/kernel/debug/hnat/qdma_txq${id}
		iptables -t mangle -A eqos -s $ip -j DSCP --set-dscp ${id}
		fi
		if [ $dl -ne 0 ]; then
		echo 2 0 0 1 ${dl} 4 4 > /sys/kernel/debug/hnat/qdma_txq${idpair}
		iptables -t mangle -A eqos -d $ip -j DSCP --set-dscp ${idpair}
		fi
		else
		iptables -t mangle -D eqos -s $ip -j MARK --set-mark 0x99
		iptables -t mangle -D eqos -d $ip -j MARK --set-mark 0x99
		if [ $up -ne 0 ]; then
		iptables -t mangle -A eqos -s $ip -j MARK --set-mark 0x99
		fi
		if [ $dl -ne 0 ]; then
		iptables -t mangle -A eqos -d $ip -j MARK --set-mark 0x99
		fi
		
		fi
		tc class add dev $dev parent 1:1 classid 1:1$cnt htb rate ${dl}kbit ceil ${dl}kbit
		tc filter add dev $dev parent 1:0 protocol ip u32 match ip dst $ip flowid 1:1$cnt
		
		tc class add dev ${dev}-ifb parent 1:1 classid 1:1$cnt htb rate ${up}kbit ceil ${up}kbit
		tc filter add dev ${dev}-ifb parent 1:0 protocol ip u32 match ip src $ip flowid 1:1$cnt
	;;
	*)
		echo "Usage: $0 <command> [options]"
		echo "Commands:"
		echo "  start dl_rate up_rate       #Total bandwidth (Mbit/s)"
		echo "  stop"
		echo "  add ip dl_rate up_rate      #Limiting the bandwidth of a single IP (kbit/s)"
		echo "Example:"
		echo "  $0 start 30 20              # Total bandwidth: down 30Mbit/s up 20Mbit/s"
		echo "  $0 add 192.168.22.12 10 2   # down 10kbit/s  up 2kbit/s"
	;;
esac
