#!/bin/sh /etc/rc.common

if [ ! -f /sys/class/gpio/export ]; then
        exit 0
fi

### enable M.2 5G RM500U-CN Module Power ###
echo 431 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio431/direction
echo   0 > /sys/class/gpio/gpio431/value
